name: NHDTB

services:
  mysql:
    image: mysql
    container_name: NHDTB-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: NHDTB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - NHDTB_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  NHDTB_mysql_data: